project_name: "media-renamer"
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/media-renamer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
release:
  draft: true
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
